spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test_db
        username: test_user
        password: test_password
app:
    server:
        name: test-server
        detail: Testing Environment
