spring:
    datasource:
        url: jdbc:mysql://localhost:3306/prod_db
        username: prod_user
        password: prod_password
app:
    server:
        name: prod-server
        detail: Production Environment
